version: '3.7'
services:
  digitron-db:
    image: postgres:14.5
    container_name: digitron-postgres
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.data/postgres:/var/lib/postgresql
    ports:
      - ${DB_PORT}:5432
